---
name: Test
permissions: read-all

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - '**/*.test.[jt]sx?'
      - '**/*.spec.[jt]sx?'
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node v22
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      - name: Cache Cypress Binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: cypress-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: CRM Client - Cypress Testing
        run: pnpm --filter @apps/crm-client cypress:e2e
      # - name: CRM Client - Cypress Binary
      #   uses: cypress-io/github-action@v6
      #   with:
      #     working-directory: ./
      #     project: apps/crm/client
      #     install: true
      #     runTests: false
      # env:
      #   CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
      # - name: CRM Client - Cypress Testing
      #   uses: cypress-io/github-action@v6
      #   with:
      #     working-directory: apps/crm/client
      #     command: pnpm run cypress:e2e
      #     install: false
      #     component: false
      #     record: false
      #     publish-summary: true
      # env:
      #   CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

      - name: CRM Client - Vitest
        run: pnpm --filter "./apps/crm/client" vitest:test

      - name: CRM Server - Vitest
        run: pnpm --filter "./apps/crm/server" vitest:test
